baseurl = "https://www.biodong.com"
languageCode = "en-us"
title = "Dong | 董"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = "biodong"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    cn = "/cn/:year/:slug/"
    en = "/en/:year/:slug/"
    
[[menu.main]]
    name = "About"
    url = "/en/about/"
    weight = 1

[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 2

[[menu.en]]
    name = "Home"
    url = "/"
    weight = 1
    
[[menu.en]]
    name = "Posts"
    url = "/en/"
    weight = 2


[[menu.en]]
    name = "About"
    url = "/en/about/"
    weight = 3
    
[[menu.en]]
    name = "Research"
    url = "/research/"
    weight = 4

[[menu.en]]
    name = "中文"
    url = "/cn/"
    weight = 4

[[menu.main]]
    name = "关于"
    url = "/cn/about/"
    weight = 3

[[menu.main]]
    name = "科研"
    url = "/research/"
    weight = 4

[[menu.cn]]
    name = "首页"
    url = "/"
    weight = 1
    
[[menu.cn]]
    name = "关于"
    url = "/cn/about/"
    weight = 2

[[menu.cn]]
    name = "博文"
    url = "/cn/"
    weight = 3

[[menu.cn]]
    name = "科研"
    url = "/research"
    weight = 4

[[menu.cn]]
    name = "English"
    url = "/en/"
    weight = 5

[params]
    description = ""
    footer = "&copy; [Dong 2021 ](https://www.biodong.com) - [Tags](/tags/) - [RSS](/index.xml)"
    customJS = ["js/external-link.js"]
    githubContentURL = "https://github.com/YonghuiDong/Website/edit/master/content/"
    dateFormat = "2006-01-02" # "2006-01-02, Mon, "
    
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "tex"]
    highlightjsTheme = "atom-one-light"

 [markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.asciidocExt]
    backend = 'html5'
    extensions = []
    failureLevel = 'fatal'
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = 'unsafe'
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 2 

[params.author]
      en = "Yonghui Dong"
      cn = "Yonghui Dong"

[params.logo.en]
     img = "/logo/go.png"
     url = "/"
     alt = "Hi there"
     tag = ""

[params.lang.edit]
     post = "编辑该页"
     cn = "编辑该页"

