---
title: Jogging Is My Happy Hour
slug: jogging
disable_comments: yes
editor_options:  
  chunk_output_type: console
--- 

```{r, echo = FALSE, message=FALSE, warning = FALSE, results='hide'}
getwd() 
```

```{r, echo = FALSE, message=FALSE, warning = FALSE, results = 'hold'}
library(plotly)
library(lubridate)

#(1) read my data
mydata <- read.csv('../static/data/jogging.csv', header = T)  
mydata$Date <- as.factor(mydata$Date)
mydata$Date <- as.Date(mydata$Date, format = "%d/%m/%Y")

#(2) add more date attributes
years <- year(ymd(mydata$Date))
months <- month(ymd(mydata$Date), label = TRUE, abbr = FALSE)
weeks <- week(ymd(mydata$Date))
wdays = wday(ymd(mydata$Date), label = TRUE, week_start = 3) ## week_start is import for the x axis
days = day(ymd(mydata$Date))
mydata2 <- data.frame(years, months, weeks, wdays, days, mydata)

#(3) subset my data 
## get now
year_now <- year(ymd(Sys.Date()))
month_now <- month(ymd(Sys.Date()), label = TRUE, abbr = FALSE)
week_now <- week(ymd(Sys.Date()))
wday_now <- wday(ymd(Sys.Date()), label = TRUE, week_start = 2)
day_now <- day(ymd(Sys.Date()))
## subset the data
mydata3 <- mydata2 %>% 
  filter(mydata2$years == year_now & mydata2$months == month_now)

#(4) ggplot
p <- ggplot(mydata3, aes(x = wdays, y = weeks)) +
    geom_text(label = mydata3$days, size = 4) + 
    theme(axis.ticks = element_blank()) +
    theme(axis.title = element_blank()) +
    theme(axis.text=element_text(size=12, face="bold")) + 
    theme(panel.background = element_rect(fill = "transparent"))+
    geom_point(aes(color = Distance), size = 14, alpha = 0.3) +
    scale_y_continuous(expand = c(0, 0.5), trans = "reverse", 
                       breaks = unique(mydata3$weeks)) + 
    labs(colour="Distance (KM)") +
    scale_color_distiller(palette = "Spectral") + 
    annotate("text", x = wday_now, y = week_now, label = day_now, size = 4, 
             color = "red", fontface = "bold" )
  
ggplotly(p, width = 650) %>%
  layout(margin = list(l = 50, r = 50, b = 30, t = 30, pad = 4),
         title = paste("My Jogging Calender in", month_now, year_now),
         titlefont = list(size = 20))
```

******

```{r, echo = FALSE, message=FALSE, warning = FALSE, results = 'hold'}
##(1) get the data of this year
mydata4 <- mydata3 <- mydata2 %>% 
  filter(mydata2$year == year_now)
  
##(2) plot
sd <- highlight_key(mydata4, ~ months, "Select a month") 
base <- plot_ly(sd, color = I("black"), width = 550) %>%
  group_by(years, months)

p1 <- base %>%
  summarise(km = sum(Distance)) %>%
  add_bars(x = ~ km, y = ~ months, alpha = 0, width = 0.6, hoverinfo = "x+y") %>%
  layout(
    barmode = "overlay",
    xaxis = list(title = "Monthly Distance (KM)"),
    yaxis = list(title = "",
                 ticklen = 6)
  ) 


p2 <- base %>%
  add_markers(sizes = c(0, 200), x = ~ days, y = ~ Distance, 
              size = ~ Distance, alpha = 0.1) %>%
  layout(xaxis = list(title = "dates",
                      zeroline = FALSE),
         yaxis = list(title = "Distance (KM)",
                      zeroline = FALSE))

subplot(p2, p1,  nrows = 2, titleX = TRUE, titleY = TRUE, 
        margin = 0.05, heights = c(0.4, 0.6)) %>% 
  hide_legend() %>%
  highlight(dynamic = F, on = "plotly_click", off = "plotly_relayout", selectize = TRUE, 
            color = "lightskyblue", defaultValues = month_now) %>%
  layout(margin = list(l = 50, r = 50, b = 40, t= 40, pad = 4),
         title = "My Jogging History", titlefont = list(size = 20))
```

