---
title: "Yonghui Dong's CV"
author: yonghui Dong
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ["my_custom.css", "resume"]
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
---

```{css, echo=FALSE}
.pagedjs_page:not(:first-of-type) {
  --sidebar-width: 4rem;
  --main-width: calc(var(--content-width) - var(--sidebar-width));
  --decorator-horizontal-margin: 0.2in;
}
```

Aside
================================================================================

Contact {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> yonghui.dong@gmail.com

- <i class="fa fa-github"></i> [github.com/YonghuiDong](https://github.com/yonghuidong)

- <i class="fab fa-researchgate"></i> [ResearchGate](https://www.researchgate.net/profile/Yonghui_Dong)

- <i class="fa fa-phone"></i> +972586302077


Research Interests {#interest}
--------------------------------------------------------------------------------

<i class="fa fa-angle-right"></i> Mass Spectrometry Imaging

<i class="fa fa-angle-right"></i> Metabolomics

<i class="fa fa-angle-right"></i> Chemoinformatics


Skills {#skills}
--------------------------------------------------------------------------------

- **Programming:** 

<i class="fa fa-angle-right"></i> R (9/10)

<i class="fa fa-angle-right"></i> Python (7/10)

<i class="fa fa-angle-right"></i> Git/GitHub (8/10)

<i class="fa fa-angle-right"></i> Docker (7/10)

Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Last updated on `r Sys.Date()`.

Main
================================================================================

Yonghui Dong {#title}
--------------------------------------------------------------------------------

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------
### Trento University, Italy <br> </br> Fondazione Edmund Mach, Italy 

</br>
PhD in Analytical Chemistry

N/A

Oct.2010 - Jun.2014

Supervisors: Dr.Pietro Franceschi, Dr.Fulvio Mattivi & Prof.Guella Graziano

Thesis: Mass Spectrometry Imaging: Looking Fruits at Molecular Level


### Max Planck Institute for Chemical Ecology, Germany 

</br>
Visiting PhD student 

N/A

Jun.2012 - Dec.2012

Supervisor: Dr.Ales Svatos

Project: Mass spectrometry imaging of surface lipids on intact _Drosophila melanogaster_ flies


### Bologna University, Italy <br> </br> Munich University of Technology, Germany <br> </br> BOKU University, Austria

</br>
Triple MSc. in Horticulture Science

N/A

Sep.2008 - Sep.2010

Supervisors: Dr. Stefano Tartarini, Dr. Luca Dondini & Prof. Dieter Treutter

Thesis: QTL Analysis of Sugars and Organic Acids in Apricot

### Northwest A&F University, China 

</br>
BSc. in Bioengineering

N/A

Sep.2003 - Jun.2006

Supervisor: Prof. Zhihui Cheng

Thesis: Effects of UV-C on the control of cucumber powdery mildew

Research Experience {data-icon=flask data-concise=true}
--------------------------------------------------------------------------------

### Researcher

</br>
Mass Spectrometry Imaging Unit, Weizmann Institute of Science, Israel

N/A

June. 2022 - Now

### Researcher

</br>
Blavatnik Center for Drug Discovery, Tel Aviv University, Israel

N/A

Jan. 2021 - May.2022


### Postdoctoral Research Fellow

</br>
Weizmann Institute of Science, Israel

N/A

Dec. 2014 - Dec. 2020

</br>
Supervisor: Prof. Asaph Aharoni


### Research Associate

</br>
Trento University, Italy

N/A

Jul. 2014 - Nov.2014

</br>
Supervisor: Prof.Guella Graziano


Publications {data-icon=file}
-------------------------------------------------------------------------------
### 25. PICA: Pixel Intensity Correlation Analysis for Deconvolution and Metabolite Identification in Mass Spectrometry Imaging

Analytical Chemistry

N/A

2023

<u>**Yonghui Dong**</u>, Nir Shachaf, Liron Feldberg, Ilana Rogachev, Uwe Heinig, Asaph Aharoni


### 24. Image to insight: exploring natural products through mass spectrometry imaging

Natural product reports, 7, 1510-1530

N/A

2022

<u>**Yonghui Dong**</u>, Asaph Aharoni


### 23. TMT-based quantitative proteomics reveals protein biomarkers from cultured Pacific abalone (Haliotis discus hannai) in different regions

Food Chemistry: X, https://doi.org/10.1016/j.fochx.2022.100355

N/A

N/A

YimuLuan, <u>**Yonghui Dong**</u> (co-first author), Xuyuan Duan, Xiuli Wang, Yue Pang, Qingwei Li, MengGou


### 22. The metabolic and proteomic repertoires of periderm tissue in skin of the reticulated Sikkim cucumber fruit

Horticulture Research, doi: 10.1093/hr/uhac092

N/A

N/A

Gulab Chand Arya,  <u>**Yonghui Dong**</u> (co-first author),  Uwe Heinig,  Nir Shahaf,  Yana Kazachkova, Elinor Aviv-Sharon,  Gal Nomberg,  Ofir Marinov,  Ekaterina Manasherova,  Asaph Aharoni, Hagai Cohen

### 21. Quantitative Trait Loci Mapping and Identification of Candidate Genes Linked to Fruit Acidity in Apricot Q13 (_Prunus armeniaca L._)

Frontiers in Plant Science, doi: 10.3389/fpls.2022.838370

N/A

N/A

Luca Dondini, Cecilia Domenichini, <u>**Yonghui Dong**</u>, Fabio Gennari, Daniele Bassi, Stefano Foschi, Martina Lama, Marco Adami, Paolo De Franceschi, Claudia Cervellati, Lorenzo Bergonzoni, Sara Alessandri, Stefano Tartarini

### 20. RawHummus: an R Shiny App for Automated Raw Data Quality Control in Metabolomics

Bioinformatics, btac040

N/A

N/A

<u>**Yonghui Dong**</u>, Yana Kazachkova, Meng Gou, Liat Morgan, Tal Wachsman, Ehud Gazit, Rune Isak Dupont Birkler

### 19. CCWeights: an R package and web application for automated evaluation and selection of weighting factors for accurate quantification using linear calibration curve

Bioinformatics Advances, 1(1), vbab029

N/A

2021

<u>**Yonghui Dong**</u>, Tal Wachsman, Liat Morgan, Ehud Gazit, Rune Isak Dupon Birkler

### 18. Characterization of the PRODUCTION OF ANTHOCYANIN PIGMENT 1 Arabidopsis Dominant Mutant using DLEMMA Dual Isotope Labeling Approach

Phytochemistry, 186

N/A

N/A

<u>**Yonghui Dong**</u>, Liron Feldberg, Ilana Rogachev, Asaph Aharoni

### 17. The GORKY glycoalkaloid transporter is indispensable for preventing tomato bitterness

Nature Plant, 7, 468-480

N/A

N/A

Yana Kazachkova, Itay Zemach, Sayantan Panda , Samuel Bocobza , Andrii Vainer, Ilana Rogachev, <u>**Yonghui Dong**</u>, Shifra Ben-Dor , Dorottya Veres , Christa Kanstrup , Sophie Konstanze Lambertz, Christoph Crocoll, Yangjie Hu, Eilon Shani, Simon Michaeli, Hussam Hassan Nour-Eldin, Dani Zamir, Asaph Aharoni


### 16. High mass resolution, spatial metabolite mapping enhances the current plant gene and pathway discovery toolbox

New Phytologist, 2020, 228:1986-2002.

N/A

2020

<u>**Yonghui Dong**</u>, Prashant Sonawane, Hagai Cohen, Guy Polturak, Liron Feldberg, Shelly Hen Avivi, Ilana Rogachev, Asaph Aharoni

### 15. Rhizosphere microbiome mediates systemic root metabolite exudation by root-to-root signaling

Proceedings of the National Academy of Sciences, 2020, 7:3874-3883.

N/A

N/A

Elisa Korenblum, <u>**Yonghui Dong**</u>, Jedrzej Szymanski, Sayantan Panda, Adam Jozwiak, Hassan Massalha, Sagit Meir, Ilana Rogachev, Asaph Aharoni


### 14. Miso: an R package for multiple isotope labeling assisted metabolomics data analysis

Bioinformatics, 2019, 35:3524-3526.

N/A

2019

<u>**Yonghui Dong**</u>, Liron Feldberg, Asaph Aharoni

### 13. A Multilevel Study of Melon Fruit Reticulation Provides Insight into Skin Ligno-suberization Hallmarks

Plant Physiology, 2019, 179:1486-1501.

N/A

N/A

Hagai Cohen, <u>**Yonghui Dong**</u>, Jedrzej Szymanski, Justin Lashbrooke, Sagit Meir, Efrat Almekias-Siegl, Viktoria Valeska Zeisler-Diehl, Lukas Schreiber, Asaph Aharoni

### 12. In plaque-mass spectrometry imaging of a bloom-forming alga during viral infection reveals a metabolic shift towards odd-chain fatty acid lipids

Nature Microbiology, 2019, 3:527-538.

N/A

N/A

Guy Schleyer, Nir Shahaf, Carmit Ziv, <u>**Yonghui Dong**</u>, Roy A Meoded, Eric JN Helfrich, Daniella Schatz, Shilo Rosenwasser, Ilana Rogachev, Asaph Aharoni, Jörn Piel, Assaf Vardi


### 11. DLEMMA-MS-imaging for identification of spatially localized metabolites and metabolic network map reconstruction

Analytical Chemistry, 2018, 17:10231-10238.

N/A

2018

Liron Feldberg, <u>**Yonghui Dong</u>** (co-first author), Uwe Heinig, Ilana Rogachev, Asaph Aharoni

### 10. Mapping of cell wall aromatic moieties and their effect on hygroscopic movement in the awns of stork’s bill

Cellulose, 2018, 25: 3827-3841.

N/A

N/A

Yael Abraham, <u>**Yonghui Dong**</u>, Asaph Aharoni, Rivka Elbaum


### 09. TLC surface integrity affects the detection of alkali adduct ions in TLC-MALDI analysis

Analytical and Bioanalytical Chemistry, 2017, 409: 5661-5666.

N/A

2017

<u>**Yonghui Dong**</u>, Ruggero Ferrazza, Andrea Anesi, Graziano Guella, Pietro Franceschi

### 08. Engineered gray mold resistance, antioxidant capacity, and pigmentation in betalain-producing crops and ornamentals

Proceedings of the National Academy of Sciences, 2017, 14: 9062-9067.

N/A

N/A

Guy Polturak, Noam Grossman, David Vela-Corcia, <u>**Yonghui Dong**</u>, Adi Nudel, Margarita Pliner, Maggie Levy, Ilana Rogachev, Asaph Aharoni

### 07. Impact of tissue surface properties on the desorption electrospray ionization imaging of organic acids in grapevine stem

Rapid Communications in Mass Spectrometry, 2016, 30: 711-718.

N/A

N/A

<u>**Yonghui Dong**</u>, Graziano Guella, Pietro Franceschi 

### 06. More than pictures: when MS imaging meets histology

Trends in Plant Science, 2016, 21: 686-698.

N/A

2016

<u>**Yonghui Dong**</u>, Bin Li, Asaph Aharoni     

### 05. Sample preparation for mass spectrometry imaging of plant tissues: a review

Frontiers in plant science, 2016.

N/A

N/A

<u>**Yonghui Dong**</u>, Bin Li, Sergey Malitsky, Ilana Rogachev, Asaph Aharoni, Filip Kaftan, Aleš Svatoš, Pietro Franceschi

### 04. Identification of microRNAs and their targets associated with fruit-bagging and subsequent sunlight re-exposure in the “Granny Smith” apple exocarp using high-throughput sequencing

Frontiers in plant science, 2016.

N/A

N/A

Dong Qu, Fei Yan, Rui Meng, Xiaobing Jiang, Huijuan Yang, Ziyi Gao, <u>**Yonghui Dong**</u>, Yazhou Yang, Zhengyang Zhao

### 03. Analytical capabilities of mass spectrometry imaging and its potential applications in food science

Trends in Food Science & Technology, 2016, 47: 50-63.

N/A

N/A

Bin Li, Sage JB Dunham, <u>**Yonghui Dong**</u>, Sohee Yoon, Maomao Zeng, Jonathan V Sweedler

### 02. High production of small organic dicarboxylate dianions by DESI and ESI

Journal of The American Society for Mass Spectrometry, 2015, 26: 386-389.

N/A

2015

<u>**Yonghui Dong**</u>, Graziano Guella, Fulvio Mattivi, Pietro Franceschi

### 01. Combining intensity correlation analysis and MALDI imaging to study the distribution of flavonols and dihydrochalcones in Golden Delicious apples

Journal of experimental botany, 2012, 63: 1123-1133.

N/A

2012

Pietro Franceschi, <u>**Yonghui Dong**</u>, Kerstin Strupat, Urska Vrhovsek, Fulvio Mattivi

Software {data-icon=cubes}
--------------------------------------------------------------------------------

### 01. MSbox

A series of common mass spectrometry tools. It allows checking element isotopes, calculating (isotope labelled) exact monoisitopic mass, m/z values and mass accuracy, and inspecting possible contaminant mass peaks, examining possible adducts in electrospray ionization (ESI) and Matrix-Assisted Laser Desorption Ionization (MALDI) ion sources.

N/A

N/A

[GitHub](https://github.com/YonghuiDong/MSbox)

### 02. Miso

An efficient tool for fishing out labeled molecules from single, dual or multiple isotope labeling experiment.

N/A

N/A

[GitHub](https://github.com/YonghuiDong/Miso), [Scholar](https://doi.org/10.1093/bioinformatics/btz092)

### 03. CCWeights

The accuracy of any analytical method highly depends on the selection of an appropriate calibration model. CCWeights is designed to automatically assess & select the best weighting factors (WF) for accurate metabolite quantification using the linear calibration curve.

N/A

N/A

[GitHub](https://github.com/YonghuiDong/CCWeights), [Scholar](https://doi.org/10.1093/bioadv/vbab029)

### 04. RawHummus

Robust and reproducible data is essential to ensure high-quality results for metabolomics studies where detector sensitivity drifts, retention time, and mass accuracy shifts frequently occur. RawHummus is designed to automatically detect measurement bias &  verify system consistency.

N/A

N/A

[GitHub](https://github.com/YonghuiDong/RawHummus), [Scholar](https://doi.org/10.1093/bioinformatics/btac040)

Posters & Talks {data-icon=tv}
--------------------------------------------------------------------------------
### How vampires suck blood? (Talk)

First Israel Metabolomics Meeting (Israel)

N/A

2022

### Software solutions in untargeted and targeted metabolomics (Poster)

First Israel Metabolomics Meeting (Israel)

N/A

N/A

### Pixel-wise Colocalization Analysis for Metabolite Identification in Mass Spectrometry Imaging (Talk)

Waterman Seminar Series on Bioinformatics (Germany)

N/A

2021

### Application of MS Imaging in Plant Sciences (Talk)

Mass Spectrometry Imaging Symposium (France)

N/A

2017

### More than Pictures: When MS Imaging Meets Histology (Talk)

Spring School for Advanced Imaging in Biological Research (Israel)

N/A

N/A

### Mass Spectrometry Imaging of Plant Metabolites (Poster)

Isranalytica 2015 (Israel)

N/A

2015

### Tissue Surface Properties Jeopardize Quantitative DESI Imaging of Organic Aicds in Grapevine Stem (Poster)

20th International Mass Spectrometry Conference (Switzerland)

N/A

2014

### MS Imaging of Metabolites in Fruits (Poster)

3rd MS Food day (Italy)

N/A

2013

### MS Imaging of Small Metabolites in Fruits (Talk)

Ourense Conference on Imaging Mass Spectrometry (Spain)

N/A

2012


Honors & Awards {data-icon=award}
--------------------------------------------------------------------------------

### COST Action FA1101 trainee fellowship in saffronomics, Spain

N/A

N/A

2014

### Trento University PhD scholarship, Italy

N/A

N/A

2011

### FEM GMPF scholarship, Italy

N/A

N/A

2010

### Erasmus Mundus Scholarship, European Union

N/A

N/A

2008

### Undergraduate Mathematical Modeling Contest, First Prize, China

N/A

N/A

2005
